server:
  port: 8080
wx:
  mp:
    app-id: wx5468b85e4ed6fec9
    secret: 5e2aef50b043166c41e2652b03e36685
    token: yunzhi

spring:
  datasource:
    url: "jdbc:mysql://localhost:3310/qrcode?characterEncoding=utf-8"
    username: "root"
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL8Dialect"
    hibernate:
      ddl-auto: update